#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Mysql Password
#--------------------------------------------------------------------------
#
# This file will display the MySQL password
#
#/

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

setsail

MYSQLPASS=$(grep '^password=' /home/larasail/.my.cnf | sed -e "s/^password='//" -e "s/'$//")

bar
cyan "| MySQL Password:"
cyan "| $MYSQLPASS"
bar
